library_project/library_app/urls.py
from django.urls import path
from .views import signup,login,logout,allbooks,search,addbook,deletebook,issuerequest,myissues,issue_book,return_book,requestedissues,trend,report_view

urlpatterns = [ 
    path('',allbooks,name='home'),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    
    path('search/',search),
    # path('sort/',sort),
    path('addbook/',addbook),
    path('deletebook/<int:bookID>/',deletebook),
    path('request-book-issue/<int:bookID>/',issuerequest),
    path('my-issues/', myissues, name='my_issues'),
    path('all-issues/',requestedissues),
    path('issuebook/<int:issueID>/',issue_book),
    path('return-book/<int:issue_id>/', return_book, name='return_book'),
    
    path('trend/',trend,name='trend'),
    path('report/', report_view, name='report_view'),
]

library_project/library_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static


admin.site.index_title='Library Management'
admin.site.site_header='Admin Dashboard' 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')),  # Include your app's URLs
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library_project/library_app/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone

class Author(models.Model):
    name=models.CharField(max_length=350)
    description=models.CharField(max_length=450)
    def __str__(self):
        return self.name
    
class Book(models.Model):
    name=models.CharField(max_length=350)
    author=models.ForeignKey(Author,on_delete=models.CASCADE)
    image=models.ImageField()
    category=models.CharField(max_length=220)
    quantity = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.name

    
class Member(models.Model):
    first_name=models.CharField(max_length=120)
    last_name=models.CharField(max_length=120)
    member_id=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    # def total_debt(self):
    #     return sum(transaction.charges for transaction in self.transaction_set.filter(returned=False))
    
class Transaction(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    issued = models.BooleanField(default=False)
    issued_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    returned = models.BooleanField(default=False)
    return_date = models.DateTimeField(auto_now=False, auto_created=False, auto_now_add=False, null=True, blank=True)
    charges = models.DecimalField(max_digits=10, decimal_places=2, null=True)


    def __str__(self):
        return f"{self.member} - {self.book}"

library_project/templates/library/addbook.html
{% extends 'base.html' %} {% block heading %} Add Book {% endblock heading %}
<!--  -->
{% block content %}

<form
  class="w-2xl sm:w-1/2 max-w-lg flex flex-col mx-auto"
  method="POST"
  action="/addbook/"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="name">Name</label>
    <input
      class="px-2 py-1 bg-transparent border-white border-2 rounded text-gray-800"
      type="text"
      placeholder="name"
      name="name"
    />
  </div>
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="category">Category</label>
    <input
      class="px-2 py-1 bg-transparent border-white border-2 rounded text-gray-800"
      type="text"
      placeholder="category"
      name="category"
    />
  </div>
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="book-image">Image</label>
    <input
      class="px-2 py-1 bg-transparent border-white border-2 rounded text-gray-800"
      type="file"
      accept="image/*"
      name="book-image"
    />
  </div>
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="author">Author</label>
    <select
      class="rounded border border-red-300 py-2 focus:outline-none focus:ring-2 focus:ring-red-200 focus:border-red-500 text-base pl-3 pr-10 text-gray-800"
      name="author"
    >
      <option value="">Choose Author</option>
      {%for author in authors %}
      <option value="{{author.id}}">{{author.name}}</option>
      {% endfor %}
    </select>
  </div>
  <button
    class="text-white place-self-center hover:shadow-md text-xl w-full rounded bg-pink-500 px-4 py-1 mt-8"
    type="submit"
  >
    Add Book
  </button>
</form>
{% endblock content%}

library_project/templates/library/allissues.html
{% extends 'base.html' %} {% block heading %} All Issues {% endblock heading %}
{% block content %}
<form
  class="w-full flex flex-col sm:flex-row sm:items-center"
  action="/all-issues/"
>
  <label class="text-lg" for="memberID">Search Member :</label>
  <input
    class="w-full sm:w-1/3 px-2 py-1 bg-transparent border-white border-2 mt-4 sm:mt-0 sm:mx-5 rounded text-white placeholder-gray-700"
    type="text"
    name="memberID"
    id="search"
    placeholder="member id only"
  />
  <button
    class="text-white hover:shadow-md rounded mt-4 sm:mt-0 bg-blue-500 px-4 py-1"
  >
    Search
  </button>
</form>

<!--  -->
<ul class="list-disc px-4 mt-8">
  {% for issue in issues %}
  <li>
    <h3 class="text-xl tracking-wide">
      <span class="font-bold">{{issue.book.name}}</span> Issue Requested by
      <a
        target="_blank"
        href="/admin/member/{{issue.member.id}}/"
        class="font-bold hover:underline"
      >
      {{issue.member.member_id.username}}_{{issue.member.first_name}}</a
      >
    </h3>
    <h4 class="text-xs">Created at:-{{issue.created_at}}</h4>
    <div class="flex flex-row w-2/3 space-x-4 mt-4 mb-8">
      {% if user.is_superuser %} {% if issue.issued %}
      <h5 class="w-xs rounded text-md font-bold text-green-500 px-4 py-1">
        Issued
      </h5>
      {%if issue.returned %}
      <h5 class="w-xs rounded font-bold text-green-500 px-4 py-1">Returned</h5>
      {% else %}
      <a
        class="w-xs rounded bg-green-500 px-4 py-1 text-white"
        href="/returnbook/{{issue.id}}/"
        >return book</a
      >
      {% endif %} {% else %}
      <a
        class="w-xs rounded bg-blue-500 px-4 py-1 text-white"
        href="/issuebook/{{issue.id}}/"
        >issue book</a
      >
      {% endif %} {% endif %}
    </div>
  </li>
  {% empty %}
  <h2>Nothing Found</h2>
  {% endfor %}
</ul>

{% endblock %}

library_project/templates/library/home.html
{% extends 'base.html' %} {% block heading %} Books List {% endblock heading %}
<!--  -->
{% block content %}
<!-- searchbar -->
<form class="flex sm:flex-row flex-col" action="/search/">
  <div
    class="w-full md:w-1/2 l:w-1/3 flex flex-col sm:flex-row sm:items-center "
  >
    <label class="text-lg" for="search-query">Search :</label>
    <input
      class="w-full sm:w-2/3 px-2 py-1 bg-transparent border-white border-2 mt-4 sm:mt-0 sm:ml-10 rounded text-white"
      type="text"
      name="search-query"
      id="search"
    />
  </div>
  <div class="flex space-x-4 mt-4 sm:mt-0 flex-row sm:items-center">
    <button
      class="text-white hover:shadow-md rounded bg-blue-600 px-4 py-1 text-gray-100"
      name="author"
    >
      Author
    </button>
    <button
      class="hover:shadow-md bg-yellow-400 text-gray-900 rounded px-4 py-1"
      name="book"
    >
      Book
    </button>
  </div>
</form>
{% comment %} <!-- sorting alphabetically -->
<form
  class="flex flex-col sm:flex-row sm:space-x-4 mt-8 sm:items-center"
  action="/sort/"
>
  <h3>Sort :</h3>
  <select
    class="rounded focus:outline-none focus:ring-2 focus:ring-red-200 focus:border-red-500 text-base pr-3 pl-1 text-gray-900"
    name="sort_type"
    id="sort_type"
  >
    <option value="book">book</option>
    <option value="author">author</option>
  </select>
  <ul id="sortable" class="flex flex-wrap space-x-1">
    <li><button name="sort" value="A">A</button></li>
    <li><button name="sort" value="B">B</button></li>
    <li><button name="sort" value="C">C</button></li>
    <li><button name="sort" value="D">D</button></li>
    <li><button name="sort" value="E">E</button></li>
    <li><button name="sort" value="F">F</button></li>
    <li><button name="sort" value="G">G</button></li>
    <li><button name="sort" value="H">H</button></li>
    <li><button name="sort" value="I">I</button></li>
    <li><button name="sort" value="J">J</button></li>
    <li><button name="sort" value="K">K</button></li>
    <li><button name="sort" value="L">L</button></li>
    <li><button name="sort" value="M">M</button></li>
    <li><button name="sort" value="N">N</button></li>
    <li><button name="sort" value="O">O</button></li>
    <li><button name="sort" value="P">P</button></li>
    <li><button name="sort" value="Q">Q</button></li>
    <li><button name="sort" value="R">R</button></li>
    <li><button name="sort" value="S">S</button></li>
    <li><button name="sort" value="T">T</button></li>
    <li><button name="sort" value="U">U</button></li>
    <li><button name="sort" value="V">V</button></li>
    <li><button name="sort" value="W">W</button></li>
    <li><button name="sort" value="X">X</button></li>
    <li><button name="sort" value="Y">Y</button></li>
    <li><button name="sort" value="Z">Z</button></li>
  </ul>
</form> {% endcomment %}
<!-- all books -->


<ul
  class=" mt-10 md:px-4 lg:px-12 xl:px-0 grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4"
>
  {% for book in books %}
  <li class="mb-12 md:mb-4 mx-auto text-center">
    <h2 class="text-lg font-bold">Book: {{book.name}}</h2>
    <h4 class="text-xs font-regular text-white pt-2">Author: {{book.author}}</h4>
    <h4 class="text-xs font-regular text-white pt-2">Category: {{book.category}}</h4>
    <div class="grid place-items-center p-2">
      <img
        src="{{book.image.url}}"
        alt="{{book.name}}"
        height="100"
        width="100"
        class="mb-4"
      />
      <h4 class="text-xs font-regular text-white pt-2">Quantity: {{book.quantity}}</h4> <!-- Adjusted to display quantity_available -->
    </div>
    {% if not user.is_superuser and not user.is_anonymous %}
    <!--  -->

    {% if book in issuedbooks %}
    <p class="text-green-500 font-medium">Status: issued</p>
    {% elif book in requestedbooks %}
    <p class="text-blue-500 font-medium">Status: issued requested</p>
    {% else %}

    <a
      class="text-white hover:shadow-md rounded bg-green-600 px-4 py-1"
      href="/request-book-issue/{{book.id}}/"
      >Request Issue</a
    >
    {% endif %} {% endif %} {% if user.is_superuser %}
    {% comment %} <a
      href="/admin/library/book/{{book.id}}/change/"
      class="text-white hover:shadow-md rounded bg-blue-600 px-4 py-1"
      >Edit</a
    > {% endcomment %}
    {% endif %}
  </li>

  {% endfor %}
</ul>

<!-- author search results -->
{% if 'author' in request.get_full_path %} {% for author in author_results %}

<div {% if not forloop.first %} class="my-8" {% endif %}>
  <h1 class="text-lg font-bold mb-2">{{author.name}}</h1>

  <ul class="list-disc px-4">
    {% for book in author.book_set.all %}
    <li>
      <div class="flex flex-row space-x-4">
        <h2>{{book.name}}</h2>
        {% if not user.is_superuser and not user.is_anonymous %}
        <!--  -->
        {% if book in issuedbooks %}
        <p class="text-green-500 font-medium">issued</p>
        {% elif book in requestedbooks %}
        <p class="text-blue-500 font-medium">issued requested</p>
        {% else %}
        <a
          class="text-white hover:shadow-md rounded bg-green-600 px-4 py-1"
          href="/request-book-issue/{{book.id}}/"
          >Request Issue</a
        >
        {% endif %} {% endif %}
      </div>
    </li>

    {%empty %}
    <h2>No Books</h2>
    {% endfor %}
  </ul>
</div>
{%empty %}
<h2>Not Found</h2>
{% endfor %} {% endif %}
<!-- book results -->
{% if 'book' in request.get_full_path %}
<ul
  class="mt-10 md:px-4 lg:px-12 xl:px-0 grid grid-cols-2 md:grid-cols-4 justify-items-center"
>
  {% for book in books_results %}
  <li class="px-2">
    <h2 class="text-md font-bold">{{book.name}}</h2>
    <h4 class="text-sm">{{book.author}}</h4>
    <img
      src="{{book.image.url}}"
      alt="{{book.name}}"
      height="80"
      width="80"
      class="mb-4"
    />
    {% if not user.is_superuser and not user.is_anonymous %}
    <!--  -->
    {% if book in issuedbooks %}
    <p class="text-green-500 font-medium">Status: issued</p>
    {% elif book in requestedbooks %}
    <p class="text-blue-500 font-medium">Status: issued requested</p>
    {% else %}
    <a
      class="text-white hover:shadow-md rounded bg-green-600 px-4 py-1"
      href="/request-book-issue/{{book.id}}/"
      >Request Issue</a
    >
    {% endif %} {% endif %} {% if user.is_superuser %}
    {% comment %} <a
      href="/admin/book/{{book.id}}/change/"
      class="text-white hover:shadow-md rounded bg-blue-500 px-4 py-1"
      >Edit</a
    > {% endcomment %}
    {% endif %}
  </li>
  {%empty %}
  <h2>No Books Found</h2>
  {% endfor %}
</ul>
{% endif %}
<script>
  const options = document.querySelectorAll("#sort_type option");
  options.forEach((option) => {
    if (option.textContent === "{{selected | escapejs}}") {
      option.selected = true;
    }
  });
</script>
{% endblock content %}

library_project/templates/library/myissues.html
{% extends 'base.html' %} {% block heading %} My Issues {% endblock heading %}
{% block content %}

<form
  class="flex flex-col sm:flex-row items-center justify-start"
  method="GET"
  action="/my-issues/"
>
  <button
    class="text-gray-900 w-1/2 hover:shadow-md text-md rounded bg-yellow-400 px-4 py-2"
    name="all"
    type="submit"
  >
    All Issues
  </button>
  <button
    class="text-white ml-0 mt-4 w-1/2 sm:mt-0 sm:ml-8 hover:shadow-md text-md rounded bg-green-600 px-4 py-2"
    name="issued"
    type="submit"
  >
    Issued Books
  </button>
  <button
    class="text-white ml-0 w-1/2 mt-4 sm:mt-0 sm:ml-8 hover:shadow-md text-md rounded bg-red-500 px-4 py-2"
    name="notissued"
    type="submit"
  >
    Not Issued Books
  </button>
</form>
<ul class="list-disc px-4 mt-8">
  {% for issue in issues %}
  <li class="">
    <h3 class="text-xl font-semibold tracking-wide">
      {{issue.book.name}} Issue Requested
    </h3>
    <h4 class="text-xs">{{issue.created_at}}</h4>
    <div class="flex flex-row w-2/3 space-x-4 mt-4 mb-8">
      {% if issue.issued %}
      <h5 class="w-xs font-bold rounded bg-green-600 px-4 py-1">Issued</h5>
       <h5 class="w-xs font-bold text-red-500 px-4 py-1">
        Return Date : {{issue.return_date}}
      </h5> 
      {% else %}
      <h5 class="w-xs rounded font-bold text-blue-500 px-0 py-0">
        Issue Request Pending
      </h5>
      {% endif %}
      <!--  -->
      {% if issue.issued and issue.returned %}
      <h5 class="w-xs rounded font-bold bg-green-600 px-4 py-1">Returned</h5>
      {% else %}
      <form action="{% url 'return_book' issue.id %}" method="post">
        {% csrf_token %}
        <button
          class="text-black w-xs rounded font-bold bg-yellow-400 px-4 py-1"
          name="return_book"
          type="submit"
          style="transition: none;"
          onmouseover="this.style.transform='scale(1.1)'"
          onmouseout="this.style.transform='scale(1)'"
        >
          Return Book
        </button>
      </form>
      {% comment %} <h5 class="w-xs font-bold px-4 py-1">{{issue.days_no}}</h5> {% endcomment %}
      {% endif %}
    </div>
  </li>
  {% empty %}
  <h2>Nothing Found</h2>
  {% endfor %}
</ul>

{% endblock %}

library_project/templates/library/trend.html
{% extends 'base.html' %} 
{% block heading %} Trend Report {% endblock heading %}
{% block content %}
<div class="flex flex-col">
  <!-- Popular Books -->
  <h2>Popular Books</h2>
  <div class="overflow-x-auto mb-6 mt-2">
    <table class="table-auto border-collapse border border-gray-200">
      <thead>
        <tr class="bg-gray-800">
          <th class="px-4 py-2">Book Name</th>
          <th class="px-4 py-2">Total Issues</th>
          <!-- Add additional headers as needed -->
        </tr>
      </thead>
      <tbody>
        {% for book in popular_books %}
        <tr class="bg-gray-800">
          <td class="border px-4 py-2">{{ book.book__name }}</td>
          <td class="border px-4 py-2">{{ book.total_issues }}</td>
          <!-- Add additional cells as needed -->
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Highest Paying Customers -->
  <h2>Highest Paying Customers</h2>
  <div class="overflow-x-auto mt-2">
    <table class="table-auto border-collapse border border-gray-200">
      <thead>
        <tr class="bg-gray-800">
          <th class="px-4 py-2">First Name</th>
          <th class="px-4 py-2">Last Name</th>
          <th class="px-4 py-2">Total Charges</th>
          <!-- Add additional headers as needed -->
        </tr>
      </thead>
      <tbody>
        {% for customer in highest_paying_customers %}
        <tr class="bg-gray-800">
          <td class="border px-4 py-2">{{ customer.member__first_name }}</td>
          <td class="border px-4 py-2">{{ customer.member__last_name }}</td>
          <td class="border px-4 py-2">{{ customer.total_charges }}</td>
          <!-- Add additional cells as needed -->
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}